services:
  postgres:
    image: postgres:16
    container_name: taskmanager-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: taskmanagerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: taskmanager-api
    ports:
      - "7006:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=taskmanagerdb;Username=admin;Password=admin123

volumes:
  pgdata:
